"""empty message

Revision ID: 0ca57645bd01
Revises: 2d8b5982b3f5
Create Date: 2021-02-13 23:06:01.174890

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ca57645bd01'
down_revision = '2d8b5982b3f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('rut', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=180), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('birth_date', sa.String(length=15), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('rut')
    )
    op.drop_index('tra_address', table_name='trabajadores')
    op.drop_index('tra_email', table_name='trabajadores')
    op.drop_index('tra_phone', table_name='trabajadores')
    op.drop_index('tra_rut', table_name='trabajadores')
    op.drop_table('trabajadores')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trabajadores',
    sa.Column('tra_address', mysql.VARCHAR(length=180), nullable=False),
    sa.Column('tra_birth_date', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('tra_email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('tra_gender', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('tra_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tra_last_name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('tra_name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('tra_password', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('tra_phone', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('tra_rut', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('tra_status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`tra_status` in (0,1))', name='trabajadores_chk_2'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('tra_rut', 'trabajadores', ['tra_rut'], unique=True)
    op.create_index('tra_phone', 'trabajadores', ['tra_phone'], unique=True)
    op.create_index('tra_email', 'trabajadores', ['tra_email'], unique=True)
    op.create_index('tra_address', 'trabajadores', ['tra_address'], unique=True)
    op.drop_table('users')
    # ### end Alembic commands ###
