"""empty message

Revision ID: 1b44da49f147
Revises: f744648bc40f
Create Date: 2021-02-13 20:31:34.923923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b44da49f147'
down_revision = 'f744648bc40f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.String(length=180), nullable=False))
    op.add_column('users', sa.Column('birth_date', sa.String(length=15), nullable=False))
    op.add_column('users', sa.Column('gender', sa.String(length=10), nullable=False))
    op.add_column('users', sa.Column('phone', sa.String(length=15), nullable=False))
    op.add_column('users', sa.Column('rut', sa.String(length=15), nullable=False))
    op.add_column('users', sa.Column('status', sa.Boolean(), nullable=True))
    op.drop_index('last_name', table_name='users')
    op.drop_index('name', table_name='users')
    op.create_unique_constraint(None, 'users', ['address'])
    op.create_unique_constraint(None, 'users', ['rut'])
    op.create_unique_constraint(None, 'users', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('name', 'users', ['name'], unique=True)
    op.create_index('last_name', 'users', ['last_name'], unique=True)
    op.drop_column('users', 'status')
    op.drop_column('users', 'rut')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'birth_date')
    op.drop_column('users', 'address')
    # ### end Alembic commands ###
