"""empty message

Revision ID: 236606563340
Revises: 56dacfd6e298
Create Date: 2021-02-13 23:22:12.267897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '236606563340'
down_revision = '56dacfd6e298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('tra_address', table_name='trabajadores')
    op.drop_index('tra_email', table_name='trabajadores')
    op.drop_index('tra_phone', table_name='trabajadores')
    op.drop_index('tra_rut', table_name='trabajadores')
    op.drop_index('email', table_name='users')
    op.drop_index('rut', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('rut', 'users', ['rut'], unique=True)
    op.create_index('email', 'users', ['email'], unique=True)
    op.create_index('tra_rut', 'trabajadores', ['tra_rut'], unique=True)
    op.create_index('tra_phone', 'trabajadores', ['tra_phone'], unique=True)
    op.create_index('tra_email', 'trabajadores', ['tra_email'], unique=True)
    op.create_index('tra_address', 'trabajadores', ['tra_address'], unique=True)
    # ### end Alembic commands ###
