"""empty message

Revision ID: 28ff0495d658
Revises: 0ca57645bd01
Create Date: 2021-02-13 23:07:19.832499

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '28ff0495d658'
down_revision = '0ca57645bd01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trabajadores',
    sa.Column('tra_id', sa.Integer(), nullable=False),
    sa.Column('tra_email', sa.String(length=120), nullable=False),
    sa.Column('tra_rut', sa.String(length=15), nullable=False),
    sa.Column('tra_name', sa.String(length=120), nullable=False),
    sa.Column('tra_last_name', sa.String(length=120), nullable=False),
    sa.Column('tra_address', sa.String(length=180), nullable=False),
    sa.Column('tra_phone', sa.String(length=15), nullable=True),
    sa.Column('tra_birth_date', sa.String(length=15), nullable=False),
    sa.Column('tra_gender', sa.String(length=10), nullable=False),
    sa.Column('tra_password', sa.String(length=80), nullable=False),
    sa.Column('tra_status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('tra_id'),
    sa.UniqueConstraint('tra_address'),
    sa.UniqueConstraint('tra_email'),
    sa.UniqueConstraint('tra_phone'),
    sa.UniqueConstraint('tra_rut')
    )
    op.drop_index('address', table_name='users')
    op.drop_index('email', table_name='users')
    op.drop_index('phone', table_name='users')
    op.drop_index('rut', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('rut', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=180), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('birth_date', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('gender', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`status` in (0,1))', name='users_chk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('rut', 'users', ['rut'], unique=True)
    op.create_index('phone', 'users', ['phone'], unique=True)
    op.create_index('email', 'users', ['email'], unique=True)
    op.create_index('address', 'users', ['address'], unique=True)
    op.drop_table('trabajadores')
    # ### end Alembic commands ###
