"""empty message

Revision ID: 2d8b5982b3f5
Revises: 4b5e68eac29b
Create Date: 2021-02-13 23:03:26.321842

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d8b5982b3f5'
down_revision = '4b5e68eac29b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trabajadores', sa.Column('tra_address', sa.String(length=180), nullable=False))
    op.add_column('trabajadores', sa.Column('tra_birth_date', sa.String(length=15), nullable=False))
    op.add_column('trabajadores', sa.Column('tra_email', sa.String(length=120), nullable=False))
    op.add_column('trabajadores', sa.Column('tra_gender', sa.String(length=10), nullable=False))
    op.add_column('trabajadores', sa.Column('tra_id', sa.Integer(), nullable=False))
    op.add_column('trabajadores', sa.Column('tra_last_name', sa.String(length=120), nullable=False))
    op.add_column('trabajadores', sa.Column('tra_name', sa.String(length=120), nullable=False))
    op.add_column('trabajadores', sa.Column('tra_password', sa.String(length=80), nullable=False))
    op.add_column('trabajadores', sa.Column('tra_phone', sa.String(length=15), nullable=True))
    op.add_column('trabajadores', sa.Column('tra_rut', sa.String(length=15), nullable=False))
    op.add_column('trabajadores', sa.Column('tra_status', sa.Boolean(), nullable=True))
    op.drop_index('address', table_name='trabajadores')
    op.drop_index('email', table_name='trabajadores')
    op.drop_index('phone', table_name='trabajadores')
    op.drop_index('rut', table_name='trabajadores')
    op.create_unique_constraint(None, 'trabajadores', ['tra_rut'])
    op.create_unique_constraint(None, 'trabajadores', ['tra_address'])
    op.create_unique_constraint(None, 'trabajadores', ['tra_email'])
    op.create_unique_constraint(None, 'trabajadores', ['tra_phone'])
    op.drop_column('trabajadores', 'last_name')
    op.drop_column('trabajadores', 'address')
    op.drop_column('trabajadores', 'password')
    op.drop_column('trabajadores', 'name')
    op.drop_column('trabajadores', 'birth_date')
    op.drop_column('trabajadores', 'rut')
    op.drop_column('trabajadores', 'id')
    op.drop_column('trabajadores', 'email')
    op.drop_column('trabajadores', 'phone')
    op.drop_column('trabajadores', 'gender')
    op.drop_column('trabajadores', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trabajadores', sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('trabajadores', sa.Column('gender', mysql.VARCHAR(length=10), nullable=False))
    op.add_column('trabajadores', sa.Column('phone', mysql.VARCHAR(length=15), nullable=True))
    op.add_column('trabajadores', sa.Column('email', mysql.VARCHAR(length=120), nullable=False))
    op.add_column('trabajadores', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('trabajadores', sa.Column('rut', mysql.VARCHAR(length=15), nullable=False))
    op.add_column('trabajadores', sa.Column('birth_date', mysql.VARCHAR(length=15), nullable=False))
    op.add_column('trabajadores', sa.Column('name', mysql.VARCHAR(length=120), nullable=False))
    op.add_column('trabajadores', sa.Column('password', mysql.VARCHAR(length=80), nullable=False))
    op.add_column('trabajadores', sa.Column('address', mysql.VARCHAR(length=180), nullable=False))
    op.add_column('trabajadores', sa.Column('last_name', mysql.VARCHAR(length=120), nullable=False))
    op.drop_constraint(None, 'trabajadores', type_='unique')
    op.drop_constraint(None, 'trabajadores', type_='unique')
    op.drop_constraint(None, 'trabajadores', type_='unique')
    op.drop_constraint(None, 'trabajadores', type_='unique')
    op.create_index('rut', 'trabajadores', ['rut'], unique=True)
    op.create_index('phone', 'trabajadores', ['phone'], unique=True)
    op.create_index('email', 'trabajadores', ['email'], unique=True)
    op.create_index('address', 'trabajadores', ['address'], unique=True)
    op.drop_column('trabajadores', 'tra_status')
    op.drop_column('trabajadores', 'tra_rut')
    op.drop_column('trabajadores', 'tra_phone')
    op.drop_column('trabajadores', 'tra_password')
    op.drop_column('trabajadores', 'tra_name')
    op.drop_column('trabajadores', 'tra_last_name')
    op.drop_column('trabajadores', 'tra_id')
    op.drop_column('trabajadores', 'tra_gender')
    op.drop_column('trabajadores', 'tra_email')
    op.drop_column('trabajadores', 'tra_birth_date')
    op.drop_column('trabajadores', 'tra_address')
    # ### end Alembic commands ###
