"""empty message

Revision ID: 33837d18ef4e
Revises: 1b44da49f147
Create Date: 2021-02-13 20:37:05.482570

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '33837d18ef4e'
down_revision = '1b44da49f147'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=mysql.VARCHAR(length=15),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=mysql.VARCHAR(length=15),
               nullable=False)
    # ### end Alembic commands ###
