"""empty message

Revision ID: 4b5e68eac29b
Revises: 33837d18ef4e
Create Date: 2021-02-13 22:58:48.525335

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b5e68eac29b'
down_revision = '33837d18ef4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trabajadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('rut', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=180), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('birth_date', sa.String(length=15), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('rut')
    )
    op.drop_index('address', table_name='users')
    op.drop_index('email', table_name='users')
    op.drop_index('phone', table_name='users')
    op.drop_index('rut', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=180), nullable=False),
    sa.Column('birth_date', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('gender', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('rut', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`status` in (0,1))', name='users_chk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('rut', 'users', ['rut'], unique=True)
    op.create_index('phone', 'users', ['phone'], unique=True)
    op.create_index('email', 'users', ['email'], unique=True)
    op.create_index('address', 'users', ['address'], unique=True)
    op.drop_table('trabajadores')
    # ### end Alembic commands ###
