"""empty message

Revision ID: 56dacfd6e298
Revises: 8a7b7632b782
Create Date: 2021-02-13 23:13:48.009540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56dacfd6e298'
down_revision = '8a7b7632b782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trabajadores',
    sa.Column('tra_id', sa.Integer(), nullable=False),
    sa.Column('tra_email', sa.String(length=120), nullable=False),
    sa.Column('tra_rut', sa.String(length=15), nullable=False),
    sa.Column('tra_name', sa.String(length=120), nullable=False),
    sa.Column('tra_last_name', sa.String(length=120), nullable=False),
    sa.Column('tra_address', sa.String(length=180), nullable=False),
    sa.Column('tra_phone', sa.String(length=15), nullable=True),
    sa.Column('tra_birth_date', sa.String(length=15), nullable=False),
    sa.Column('tra_gender', sa.String(length=10), nullable=False),
    sa.Column('tra_password', sa.String(length=80), nullable=False),
    sa.Column('tra_status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('tra_id'),
    sa.UniqueConstraint('tra_address'),
    sa.UniqueConstraint('tra_email'),
    sa.UniqueConstraint('tra_phone'),
    sa.UniqueConstraint('tra_rut')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trabajadores')
    # ### end Alembic commands ###
