"""empty message

Revision ID: 57be31119037
Revises: 
Create Date: 2021-02-15 15:08:34.609281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57be31119037'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comunas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serv_nombre', sa.String(length=120), nullable=False),
    sa.Column('serv_detalle', sa.String(length=120), nullable=False),
    sa.Column('serv_precio', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipovivienda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trabajadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tra_email', sa.String(length=120), nullable=True),
    sa.Column('tra_rut', sa.String(length=15), nullable=False),
    sa.Column('tra_name', sa.String(length=120), nullable=False),
    sa.Column('tra_last_name', sa.String(length=120), nullable=False),
    sa.Column('tra_address', sa.String(length=180), nullable=False),
    sa.Column('tra_phone', sa.String(length=15), nullable=True),
    sa.Column('tra_birth_date', sa.String(length=15), nullable=False),
    sa.Column('tra_gender', sa.String(length=10), nullable=False),
    sa.Column('tra_password', sa.String(length=80), nullable=False),
    sa.Column('tra_status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tra_email'),
    sa.UniqueConstraint('tra_phone'),
    sa.UniqueConstraint('tra_rut')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('rut', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=180), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('birth_date', sa.String(length=15), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('rut')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('trabajadores')
    op.drop_table('tipovivienda')
    op.drop_table('servicios')
    op.drop_table('comunas')
    # ### end Alembic commands ###
