"""empty message

Revision ID: 685b0f2485a1
Revises: afb3a0146cb7
Create Date: 2021-02-23 15:24:02.154810

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '685b0f2485a1'
down_revision = 'afb3a0146cb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('address', sa.String(length=180), nullable=False))
    op.add_column('pedidos', sa.Column('ciudad', sa.String(length=180), nullable=False))
    op.add_column('pedidos', sa.Column('comuna', sa.String(length=180), nullable=False))
    op.drop_constraint('pedidos_ibfk_1', 'pedidos', type_='foreignkey')
    op.drop_column('pedidos', 'id_comuna')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('id_comuna', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('pedidos_ibfk_1', 'pedidos', 'comunas', ['id_comuna'], ['id'], ondelete='CASCADE')
    op.drop_column('pedidos', 'comuna')
    op.drop_column('pedidos', 'ciudad')
    op.drop_column('pedidos', 'address')
    # ### end Alembic commands ###
