"""empty message

Revision ID: 70c704886fdb
Revises: 57be31119037
Create Date: 2021-02-15 15:18:33.958567

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '70c704886fdb'
down_revision = '57be31119037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trabajadores', sa.Column('address', sa.String(length=180), nullable=False))
    op.add_column('trabajadores', sa.Column('birth_date', sa.DateTime(), nullable=True))
    op.add_column('trabajadores', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('trabajadores', sa.Column('fecha_registro', sa.DateTime(), nullable=True))
    op.add_column('trabajadores', sa.Column('gender', sa.String(length=10), nullable=False))
    op.add_column('trabajadores', sa.Column('last_name', sa.String(length=120), nullable=False))
    op.add_column('trabajadores', sa.Column('name', sa.String(length=120), nullable=False))
    op.add_column('trabajadores', sa.Column('password', sa.String(length=80), nullable=True))
    op.add_column('trabajadores', sa.Column('phone', sa.String(length=15), nullable=True))
    op.add_column('trabajadores', sa.Column('rut', sa.String(length=15), nullable=False))
    op.add_column('trabajadores', sa.Column('status', sa.Boolean(), nullable=True))
    op.drop_index('tra_email', table_name='trabajadores')
    op.drop_index('tra_phone', table_name='trabajadores')
    op.drop_index('tra_rut', table_name='trabajadores')
    op.create_unique_constraint(None, 'trabajadores', ['rut'])
    op.create_unique_constraint(None, 'trabajadores', ['email'])
    op.create_unique_constraint(None, 'trabajadores', ['phone'])
    op.drop_column('trabajadores', 'tra_password')
    op.drop_column('trabajadores', 'tra_status')
    op.drop_column('trabajadores', 'tra_birth_date')
    op.drop_column('trabajadores', 'tra_email')
    op.drop_column('trabajadores', 'tra_rut')
    op.drop_column('trabajadores', 'tra_gender')
    op.drop_column('trabajadores', 'tra_last_name')
    op.drop_column('trabajadores', 'tra_name')
    op.drop_column('trabajadores', 'tra_address')
    op.drop_column('trabajadores', 'tra_phone')
    op.add_column('users', sa.Column('fecha_registro', sa.DateTime(), nullable=True))
    op.alter_column('users', 'birth_date',
               existing_type=mysql.VARCHAR(length=15),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'birth_date',
               existing_type=mysql.VARCHAR(length=15),
               nullable=False)
    op.drop_column('users', 'fecha_registro')
    op.add_column('trabajadores', sa.Column('tra_phone', mysql.VARCHAR(length=15), nullable=True))
    op.add_column('trabajadores', sa.Column('tra_address', mysql.VARCHAR(length=180), nullable=False))
    op.add_column('trabajadores', sa.Column('tra_name', mysql.VARCHAR(length=120), nullable=False))
    op.add_column('trabajadores', sa.Column('tra_last_name', mysql.VARCHAR(length=120), nullable=False))
    op.add_column('trabajadores', sa.Column('tra_gender', mysql.VARCHAR(length=10), nullable=False))
    op.add_column('trabajadores', sa.Column('tra_rut', mysql.VARCHAR(length=15), nullable=False))
    op.add_column('trabajadores', sa.Column('tra_email', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('trabajadores', sa.Column('tra_birth_date', mysql.VARCHAR(length=15), nullable=False))
    op.add_column('trabajadores', sa.Column('tra_status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('trabajadores', sa.Column('tra_password', mysql.VARCHAR(length=80), nullable=False))
    op.drop_constraint(None, 'trabajadores', type_='unique')
    op.drop_constraint(None, 'trabajadores', type_='unique')
    op.drop_constraint(None, 'trabajadores', type_='unique')
    op.create_index('tra_rut', 'trabajadores', ['tra_rut'], unique=True)
    op.create_index('tra_phone', 'trabajadores', ['tra_phone'], unique=True)
    op.create_index('tra_email', 'trabajadores', ['tra_email'], unique=True)
    op.drop_column('trabajadores', 'status')
    op.drop_column('trabajadores', 'rut')
    op.drop_column('trabajadores', 'phone')
    op.drop_column('trabajadores', 'password')
    op.drop_column('trabajadores', 'name')
    op.drop_column('trabajadores', 'last_name')
    op.drop_column('trabajadores', 'gender')
    op.drop_column('trabajadores', 'fecha_registro')
    op.drop_column('trabajadores', 'email')
    op.drop_column('trabajadores', 'birth_date')
    op.drop_column('trabajadores', 'address')
    # ### end Alembic commands ###
