"""empty message

Revision ID: 8e5a4f55809f
Revises: cbbf0ead7ddc
Create Date: 2021-02-20 18:32:46.102641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e5a4f55809f'
down_revision = 'cbbf0ead7ddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bank', sa.String(length=180), nullable=False))
    op.add_column('users', sa.Column('cuenta', sa.String(length=180), nullable=False))
    op.add_column('users', sa.Column('numero_cuenta', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'numero_cuenta')
    op.drop_column('users', 'cuenta')
    op.drop_column('users', 'bank')
    # ### end Alembic commands ###
