"""empty message

Revision ID: b7cb2ae9a4b6
Revises: f3ddc93a0094
Create Date: 2021-02-23 17:03:23.000895

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b7cb2ae9a4b6'
down_revision = 'f3ddc93a0094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', mysql.VARCHAR(length=10), nullable=False))
    # ### end Alembic commands ###
