"""empty message

Revision ID: cbbf0ead7ddc
Revises: 1e048177be86
Create Date: 2021-02-20 11:43:53.867534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbbf0ead7ddc'
down_revision = '1e048177be86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ciudad', sa.String(length=180), nullable=False))
    op.add_column('users', sa.Column('comuna', sa.String(length=180), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'comuna')
    op.drop_column('users', 'ciudad')
    # ### end Alembic commands ###
