"""empty message

Revision ID: ccb6e9a4fb4a
Revises: 1edcc9e71aee
Create Date: 2021-02-16 10:44:52.858821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccb6e9a4fb4a'
down_revision = '1edcc9e71aee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('trabajadores', sa.Column('rol_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'trabajadores', 'roles', ['rol_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('rol_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'roles', ['rol_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'rol_id')
    op.drop_constraint(None, 'trabajadores', type_='foreignkey')
    op.drop_column('trabajadores', 'rol_id')
    op.drop_table('roles')
    # ### end Alembic commands ###
