"""empty message

Revision ID: d6f7427f5201
Revises: ccb6e9a4fb4a
Create Date: 2021-02-16 12:50:39.456228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6f7427f5201'
down_revision = 'ccb6e9a4fb4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos',
    sa.Column('trabajador_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('cert_antecedentes', sa.String(length=150), nullable=False),
    sa.Column('foto_cedula', sa.String(length=150), nullable=False),
    sa.Column('cert_domicilio', sa.String(length=150), nullable=False),
    sa.Column('cert_prevision', sa.String(length=150), nullable=False),
    sa.Column('cert_cotizacion', sa.String(length=150), nullable=False),
    sa.Column('dias_preferencia', sa.String(length=150), nullable=False),
    sa.Column('horarios_preferencia', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trabajador_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documentos')
    # ### end Alembic commands ###
